[global]
# Configurações para Streamlit Cloud
developmentMode = false

[server]
# Configurações do servidor
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = true

[browser]
# Configurações do navegador
gatherUsageStats = false

[theme]
# Tema personalizado (opcional)
primaryColor = "#FF6B6B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
